export const UI_OPEN_EVENT_FORM = 'UI_OPEN_EVENT_FORM'
export const UI_CLOSE_EVENT_FORM = 'UI_CLOSE_EVENT_FORM'
export const UI_TOGGLE_FILTER = 'UI_TOGGLE_FILTER'

export const CREATE_EVENT = 'CREATE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'

export const CREATED_EVENT = 'CREATED_EVENT'
export const UPDATED_EVENT = 'UPDATED_EVENT'
export const DELETED_EVENT = 'DELETED_EVENT'

export const FETCH_EVENTS = 'FETCH_EVENTS'
export const FETCHED_EVENTS = 'FETCHED_EVENTS'

export const FILTER_BY_CLUBBER = 'FILTER_BY_CLUBBER'
