export const UI_OPEN_EVENT_FORM = 'UI_OPEN_EVENT_FORM'
export const UI_CLOSE_EVENT_FORM = 'UI_CLOSE_EVENT_FORM'

export const UI_TOGGLE_CLUBBER = 'UI_TOGGLE_CLUBBER'
export const UI_TOGGLE_FILTER = 'UI_TOGGLE_FILTER'
export const UI_CHANGE_NB_MONTHS = 'UI_CHANGE_NB_MONTHS'
export const UI_CHANGE_START_MONTH = 'UI_CHANGE_START_MONTH'
export const UI_CHANGE_CONFIRMED = 'UI_CHANGE_CONFIRMED'
export const UI_TOGGLE_TAG = 'UI_TOGGLE_TAG'
export const UI_SEARCH = 'UI_SEARCH'

export const UI_SET_ONLINE = 'UI_SET_ONLINE'
export const UI_SET_OFFLINE = 'UI_SET_OFFLINE'

export const CREATE_EVENT = 'CREATE_EVENT'
export const UPDATE_EVENT = 'UPDATE_EVENT'
export const DELETE_EVENT = 'DELETE_EVENT'

export const CREATED_EVENT = 'CREATED_EVENT'
export const UPDATED_EVENT = 'UPDATED_EVENT'
export const DELETED_EVENT = 'DELETED_EVENT'

export const FETCH_EVENTS = 'FETCH_EVENTS'
export const FETCHED_EVENTS = 'FETCHED_EVENTS'
